import mongoose from 'mongoose';

const schema = new mongoose.Schema(
  {
    name: { type: String, required: true, trim: true },
    email: { type: String, required: true, unique: true, lowercase: true, trim: true },
    passwordHash: { type: String, required: true },
    role: { type: String, enum: ['USER', 'SUPER_ADMIN'], default: 'USER' },
    status: { type: String, enum: ['ACTIVE', 'DISABLED'], default: 'ACTIVE' },
    salaryCycle: {
      enabled: { type: Boolean, default: false },
      amount: { type: Number, default: 0 },
      dayOfMonth: { type: Number, default: 1, min: 1, max: 28 },
      paymentMethod: { type: String, default: 'BANK_TRANSFER' },
      lastAutoGeneratedMonth: { type: String, default: '' },
    },
    resetPasswordToken: { type: String },
    resetPasswordExpires: { type: Date },
  },
  { timestamps: true }
);

const User = mongoose.model('User', schema);
export default User;
